services:

  boinc:
    image: black98fxstc/boinc-client
    build:
      context: .
      dockerfile: boinc.Dockerfile
    user: 1000:1000
    ports:
      - 127.0.0.1:31416:31416
    volumes:
      - type: bind
        source: /srv/boinc/client/
        target: /var/lib/boinc-client/
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '6.0'
